import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ImageComponent from "./img/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <head>
        <title>Smart Bus Portal</title>
        <style>{`
          header {
            background: #1e3a8a; 
            color: white;
            text-align: center;
            padding: 20px;
            font-size: 28px;
            font-weight: bold;
            border-bottom: 4px solid #2563eb;
          }

          nav {
            background: #f1f5f9; 
            padding: 12px;
            text-align: center;
          }

          nav ul {
            list-style: none;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            gap: 20px;
          }

          nav a {
            text-decoration: none;
            color: #1e3a8a;
            font-weight: 600;
            transition: color 0.3s ease;
          }

          nav a:hover {
            color: #2563eb;
          }

          main {
            min-height: 70vh;
            padding: 20px;
          }

          footer {
            background: #1e293b; 
            color: white;
            text-align: center;
            padding: 15px;
            margin-top: 20px;
          }
        `}</style>
      </head>
      <body>
        <header>
          <h1>Smart Bus Portal</h1>
        </header>

        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li>
              <Link href="/register">Register</Link> / <Link href="/login">Login</Link>
            </li>
          </ul>
        </nav>

        <main>{children}</main>

        <footer>
          <p>&copy; {new Date().getFullYear()} Smart Bus Portal. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}